### ISSUE TITLE
kibana二次开发求助。。。

### ISSUE THREAD

**Issue by Dreamer-Somebody** [zengwenzi/hello_world#2]
你好，之前看到你在kibana那边提的一个问题。。https://github.com/elastic/kibana/issues/27282
想请教一下解决了吗？我也遇到了同样的问题。。。而且是内网，挺麻烦。。因为找不到你联系方式，只能在这里提个 issue 联系你了 ....

**Comment by zengwenzi** [comment]
我已经解决了，你先确认下你的python是不是装好了

**Comment by Dreamer-Somebody** [comment]
我直接装在C盘下才可以，看他的代码，他没找到python就会默认去找 c:/pathon27，装其他地方不行，在安装的时候就点选了把python加入到环境变量里面，然后看系统->环境变量里面也是有python的两个目录的，cmd输入python --version 也是好的。。。这些应该证明了 python 装好了吧。。。
